services:
  backend:
    image: ghcr.io/alexmos1n/film-react-nest/backend:latest
    container_name: backend
    depends_on:
      - postgres
    networks:
      - postgres_network
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    image: ghcr.io/alexmos1n/film-react-nest/frontend:latest
    container_name: frontend
    networks:
      - postgres_network
    volumes:
      - frontend_dist:/app/dist
    env_file:
      - frontend/.env

  postgres:
    image: postgres:16
    container_name: postgres
    networks:
      - postgres_network
    env_file:
      - postgres-settings/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    networks:
      - postgres_network
    env_file:
      - pgadmin-settings/.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    ports:
      - 8080:80
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - postgres_network
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - frontend_dist:/var/www/frontend:ro

networks:
  postgres_network:

volumes:
  postgres-data:
  pgadmin-data:
  frontend_dist:
